######################################################################

SHELL = /bin/bash
MAKEFLAGS += --no-print-directory

DIST_VERSIONS_DIR = ./dist

SERVER_ADDRESS    = 127.0.0.127
SERVER_PORT       = 4320

VERSION           = 0.2

VERSION_DIR       = v$(VERSION)
DIST_DIR          = $(DIST_VERSIONS_DIR)/$(VERSION_DIR)


######################################################################

.PHONY: all
all: check-version $(DIST_DIR)

.DEFAULT: all

.PHONY: clean
clean: #kill-server #<<< NOTE: just leave server running...
	@-rm -fr "$(DIST_DIR)" "webpack.config.js" >/dev/null 2>&1 || true

.PHONY: full-clean
full-clean: clean
	@-rm -fr ./node_modules >/dev/null 2>&1 || true

.PHONY: check-version
check-version:
	@./build-tools/check-version.js $(VERSION)

.PHONY: check-version install
install: ./node_modules $(DIST_DIR)

.PHONY: lint
lint: ./node_modules
#!!!	./node_modules/.bin/eslint --config .eslintrc.cjs src lib

$(DIST_DIR): ./src ./src/* ./src/*/* ./src/*/*/* ./src/*/*/*/* ./lib ./lib/* ./lib/*/* ./lib/*/*/* ./help ./help/* ./help/*/* ./node_modules README.md Makefile package.json webpack.config.js
	@make check-version
	./build-tools/build-dist.sh $(VERSION_DIR)
#!!!	make lint && ./build-tools/build-dist.sh $(VERSION_DIR)

./package-lock.json ./node_modules: ./package.json
	npm install
	touch ./package-lock.json ./node_modules

webpack.config.js: webpack.config.js.template Makefile
	@make check-version
	@>webpack.config.js
	@echo '// *** THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT ***'    >>webpack.config.js
	@echo "const version_dir = '$(VERSION_DIR)';  // (generated by Makefile)" >>webpack.config.js
	@cat webpack.config.js.template                                           >>webpack.config.js

copy-files:
	./build-tools/build-dist.sh $(VERSION_DIR) copy-only

.PHONY: test
test:
	npm test

# kill the server by performing a GET on /QUIT
# uses Linux commands: lsof, grep, cut
# server uses python (version 3)
# start the server in the directory $(DIST_VERSIONS_DIR)
.PHONY: server
server: $(DIST_DIR)
	( cd "$(DIST_VERSIONS_DIR)" && python ../build-tools/server.py $(SERVER_ADDRESS) $(SERVER_PORT) 2>&1 | tee >(grep -q -m1 '"GET /QUIT'; echo QUITTING; sleep 0.1; kill $$(lsof -itcp:$(SERVER_PORT) -sTCP:LISTEN -Fp | grep ^p | cut -c2-)) )

# uses curl
.PHONY: kill-server
kill-server:
	@if lsof -itcp:$(SERVER_PORT) -sTCP:LISTEN >/dev/null 2>&1; then echo 'sending QUIT to server'; curl -s http://$(SERVER_ADDRESS):$(SERVER_PORT)/QUIT >/dev/null 2>&1; true; fi

.PHONY: dev-server
dev-server:
	npx nodemon --watch src --watch lib --watch help --watch package.json --watch Makefile --watch .eslintrc.cjs --watch webpack.config.js --watch build-tools --watch node_modules  --ext ts,js,cjs,mjs,html,css,ico,svg,py,sh  --exec "bash -c 'make server' || exit 1"

.PHONY: client
client:
	chromium --new-window http://$(SERVER_ADDRESS):$(SERVER_PORT)/current/index.html &

.PHONY: start
start: $(DIST_DIR)
	if ! lsof -itcp:$(SERVER_PORT) -sTCP:LISTEN; then make server <&- >/dev/null 2>&1 & sleep 1; fi; make client
